export const LOAD_CHARACTORS_PROGRESS = 'LOAD_CHARACTORS_PROGRESS';
export const LOAD_CHARACTORS_SUCCESS = 'LOAD_CHARACTORS_SUCCESS';
export const LOAD_CHARACTORS_ERROR = 'LOAD_CHARACTORS_ERROR';
export const LOAD_CHARACTOR_DETAIL_PROGRESS = 'LOAD_CHARACTOR_DETAIL_PROGRESS';
export const LOAD_CHARACTOR_DETAIL_SUCCESS = 'LOAD_CHARACTOR_DETAIL_SUCCESS';
export const LOAD_CHARACTOR_DETAIL_ERROR = 'LOAD_CHARACTOR_DETAIL_ERROR';
