export const LOAD_CHARACTORS_PROGRESS = 'LOAD_CHARACTORS_PROGRESS';
export const LOAD_CHARACTORS_SUCCESS = 'LOAD_CHARACTORS_SUCCESS';
export const LOAD_CHARACTORS_ERROR = 'LOAD_CHARACTORS_ERROR';
export const SEARCH_CHARACTORS_PROGRESS = 'SEARCH_CHARACTORS_PROGRESS';
export const SEARCH_CHARACTORS_SUCCESS = 'SEARCH_CHARACTORS_SUCCESS';
export const SEARCH_CHARACTORS_ERROR = 'SEARCH_CHARACTORS_ERROR';
export const LOAD_CHARACTOR_DETAIL_PROGRESS = 'LOAD_CHARACTOR_DETAIL_PROGRESS';
export const LOAD_CHARACTOR_DETAIL_SUCCESS = 'LOAD_CHARACTOR_DETAIL_SUCCESS';
export const LOAD_CHARACTOR_DETAIL_ERROR = 'LOAD_CHARACTOR_DETAIL_ERROR';
export const CLEAR_CHARACTOR_STATES = 'CLEAR_CHARACTOR_STATES';
export const CLEAR_CHARACTOR_DETAIL = 'CLEAR_CHARACTOR_DETAIL';
export const LOAD_EPISODES_PROGRESS = 'LOAD_EPISODES_PROGRESS';
export const LOAD_EPISODES_SUCCESS = 'LOAD_EPISODES_SUCCESS';
export const LOAD_EPISODES_ERROR = 'LOAD_EPISODES_ERROR';
export const LOAD_EPISODE_DETAIL_PROGRESS = 'LOAD_EPISODE_DETAIL_PROGRESS';
export const LOAD_EPISODE_DETAIL_SUCCESS = 'LOAD_EPISODE_DETAIL_SUCCESS';
export const LOAD_EPISODE_DETAIL_ERROR = 'LOAD_EPISODE_DETAIL_ERROR';
export const LOAD_EPISODE_DETAIL_BATCH_PROGRESS =
  'LOAD_EPISODE_DETAIL_BATCH_PROGRESS';
export const LOAD_EPISODE_DETAIL_BATCH_SUCCESS =
  'LOAD_EPISODE_DETAIL_BATCH_SUCCESS';
export const LOAD_EPISODE_DETAIL_BATCH_ERROR =
  'LOAD_EPISODE_DETAIL_BATCH_ERROR';
export const CLEAR_EPISODE_STATES = 'CLEAR_EPISODE_STATES';
